version: '3.8'
services:
  openvote:
    image: ibphantom/openvote:latest
    container_name: openvote
    ports:
      - "8080:8080"  # Adjust based on your app
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - ./data:/data
    restart: unless-stopped
