version: "3.9"

services:
  openvote:
    image: ${IMAGE_OVERRIDE:-ibphantom/openvote:latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: "0"
      SECRET_KEY: "change-me"
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped
